version: '3'
services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fileserver:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./filetrade:/app/filetrade
    depends_on:
      - mongodb

  daemon:
    build: ./daemon
    volumes:
      - ./filetrade:/app/filetrade
    depends_on:
      - mongodb

volumes:
  mongo_data: